bookmanager/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	# ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^(?P<book_ISBN>[0-9-]+)/$', views.detail, name='detail'),
    url(r'^delete/$',views.delete,name='delete'),
    url(r'^update/$',views.update,name='update'),
    url(r'^addbook/$',views.addbook,name='addbook'),
    url(r'^addauthor/$',views.addauthor,name='addauthor'),
]

sjhbookmanager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'', include('bookmanager.urls', namespace="bookmanager")),
    url(r'^admin/', include(admin.site.urls)),
]

bookmanager/models.py
from django.db import models

class Author(models.Model):
	AuthorID = models.CharField(max_length=30, primary_key=True)
	Name = models.CharField(max_length=100)
	Age = models.IntegerField()
	Country = models.CharField(max_length=30)
	def __str__(self):
		return self.AuthorID


class Book(models.Model):
	ISBN = models.CharField(max_length=30, primary_key=True)
	Title = models.CharField(max_length=200)
	AuthorID = models.ForeignKey(Author)
	Publisher = models.CharField(max_length=100)
	PublishDate = models.DateField()
	Price = models.IntegerField()
	def __str__(self):
		return self.ISBN

bookmanager/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from .models import Book, Author
# Create your views here.


def index(request):
	book_list = Book.objects.all()
	if request.method == 'POST':
		search_name = request.POST.get('author_name','')
		try:
			author = Author.objects.get(Name=search_name)
			book_list_of_author = Book.objects.filter(AuthorID=author.AuthorID)
			context = {'book_list': book_list,'author_lib':book_list_of_author,'author_name':author.Name}
		except:
			book_list_of_author = ['empty']
			context = {'book_list': book_list,'author_empty':book_list_of_author,'author_name':search_name}
	else:
		context = {'book_list': book_list}
	return render(request, 'bookmanager/index.html', context)

def detail(request, book_ISBN):
	book_detail = get_object_or_404(Book, ISBN=book_ISBN)
	author_detail = get_object_or_404(Author, AuthorID=book_detail.AuthorID)
	context = {'book_detail': book_detail,'author_detail':author_detail}
	return render(request, 'bookmanager/detail.html', context)

def delete(request):
	try:
		Book.objects.get(ISBN=request.GET.get('delete_book_ISBN')).delete()
	except:
		pass
	return HttpResponseRedirect('/')

update_book=[]
def update(request):
	if request.method=='GET':
		book_detail=Book.objects.get(ISBN=request.GET.get('update_book_ISBN'))
		update_book.append(book_detail)
		context = {'book_detail': book_detail}
		return render(request, 'bookmanager/update.html', context)
	else:
		try:
			book_detail=update_book[-1]
			author=Author.objects.get(AuthorID=request.POST.get('update_AuthorID'))
		 	book_detail.AuthorID = author
			book_detail.Publisher = request.POST.get('update_Publisher')
			book_detail.PublishDate = request.POST.get('update_PublishDate')
			book_detail.Price = request.POST.get('update_Price')
			book_detail.save()
			return HttpResponseRedirect('/')
		except:
			return render(request, 'bookmanager/fail.html')

def addbook(request):
	if request.method=='POST':
		try:
			add_book = Book(ISBN = request.POST.get('add_ISBN'),
			Title = request.POST.get('add_Title'),
			AuthorID = Author.objects.get(AuthorID=request.POST.get('add_AuthorID')),
			Publisher = request.POST.get('add_Publisher'),
			PublishDate = request.POST.get('add_PublishDate'),
			Price = request.POST.get('add_Price'),)
			add_book.save()
			return render(request, 'bookmanager/success.html')
		except:
			return render(request, 'bookmanager/fail.html')
	return render(request, 'bookmanager/addbook.html')

def addauthor(request):
	if request.method=='POST':
		try:
			add_author = Author(AuthorID = request.POST.get('add_AuthorID'),
			Name = request.POST.get('add_Name'),
			Age = request.POST.get('add_Age'),
			Country = request.POST.get('add_Country'),)
			add_author.save()
			return render(request, 'bookmanager/success.html')
		except:
			return render(request, 'bookmanager/fail.html')
	return render(request, 'bookmanager/addauthor.html')

bookmanager/templates/bookmanager/addauthor.html
<ul style="list-style-type:none">
  <form action="." method='POST'>
  {% csrf_token %}
  <li>AuthorID: <input type='text' name='add_AuthorID' /></li> 
  <li>Name: <input type='text' name='add_Name' /></li> 
  <li>Age: <input type='text' name='add_Age' /></li>
  <li>Country: <input type='text' name='add_Country' /></li>
  <input type='submit' value='Save'/>
  </form>      
</ul>

bookmanager/templates/bookmanager/addbook.html
<ul style="list-style-type:none">
  <form action="." method='POST'>
  {% csrf_token %}
  <li>ISBN: <input type='text' name='add_ISBN' /></li>
  <li>Title: <input type='text' name='add_Title' /></li>
  <li>AuthorID: <input type='text' name='add_AuthorID' /></li> 
  <li>Publisher: <input type='text' name='add_Publisher' /></li> 
  <li><td>PublishDate: <input type='text' name='add_PublishDate' /></td></li>
  <li>Price: <input type='text' name='add_Price'  /></li>
  <input type='submit' value='Save'/>
  </form>      
</ul>

bookmanager/templates/bookmanager/detail.html
{% if book_detail %}
    <ul style="list-style-type:none">
        <li>Title: {{ book_detail.Title }}</li>
	    <li>ISBN: {{ book_detail.ISBN }}</li>
	    <li>AuthorID: {{ book_detail.AuthorID }}</li> 
	    <li>Publisher: {{ book_detail.Publisher }}</li> 
	    <li>PublishDate: {{ book_detail.PublishDate }}</li> 
	    <li>Price: {{ book_detail.Price }}</li>      
    </ul>
    <span>Author: </span>
   	<ul style="list-style-type:none">
   		<li>Name: {{author_detail.Name}}</li>
   		<li>Age: {{author_detail.Age}}</li>
   		<li>Country: {{author_detail.Country}}</li>
   	</ul>

{% else %}
    <p>No books are available.</p>
{% endif %}

bookmanager/templates/bookmanager/fail.html
Author doesn't exist!
<p><a href="/">Return to the main page to add.</a></p>

bookmanager/templates/bookmanager/index.html
<html>
Hello!It's me.
{% if book_list %}
<table>
    {% csrf_token %} {% for i in book_list %}
    <ul>
        <tr>
            <td>
                <li><a href="{% url 'bookmanager:detail' i.ISBN %}">{{ i.Title }}</a></li>
            </td>
            <td>
                <form action='delete/' method='GET' style='display:inline'>
                    <input type='hidden' name='delete_book_ISBN' value={{ i.ISBN }} />
                    <input type='submit' value='Delete' />
                </form>
            </td>
            <td>
                <form action='update/' method='GET' style='display:inline'>
                    <input type='hidden' name='update_book_ISBN' value={{ i.ISBN }} />
                    <input type='submit' value='Update' />
                </form>
            </td>
        </tr>
    </ul>
    {% endfor %}
</table>
{% else %}
<p>No books are available.</p>
{% endif %}

<form action='addauthor/' method='GET' style='display:inline'>
    <input type='submit' value='Add author' />
</form>

<form action='addbook/' method='GET' style='display:inline'>
    <input type='submit' value='Add book' />
</form>

<p>Input Author Name:</p>
<form action="." method='POST'>
    {% csrf_token %}
    <input type='text' name='author_name' />
    <input type='submit' value='Book Search' />
</form>

{% if author_lib %}
<p>Author {{author_name}}'s book(s)</p>
<ul>
    {% for j in author_lib %}
    <li><a href="{% url 'bookmanager:detail' j.ISBN %}">{{ j.Title }}</a></li>
    {% endfor %}
</ul>
{% endif %} {% if author_empty %}
<p>Author {{author_name}} not found.</p>
{% endif %}

    
</html>

bookmanager/templates/bookmanager/success.html
Success!
<p><a href="/">Return to the main page.</a></p>

bookmanager/templates/bookmanager/update.html
<ul style="list-style-type:none">
  <form action="." method='POST'>
  {% csrf_token %}
  <input type='hidden' name='update_book_ISBN' value={{ book_detail.ISBN }} />
  <li>AuthorID: <input type='text' name='update_AuthorID' value={{ book_detail.AuthorID }} /></li> 
  <li>Publisher: <input type='text' name='update_Publisher' value="{{ book_detail.Publisher }}" /></li> 
  <li><td>PublishDate: <input type='text' name='update_PublishDate' value ={{book_detail.PublishDate|date:"Y-m-d"}} /></td></li>
  <li>Price: <input type='text' name='update_Price' value={{ book_detail.Price }} /></li>
  <input type='submit' value='Save'/>
  </form>      
</ul>